### PR TITLE
Add support for options with multiple values

### PR DESCRIPTION
**Pull request by dvd-88**
# Description

As it is described in the AWS CDK v2 [documentation](https://docs.aws.amazon.com/cdk/v2/guide/cli.html), section "Specifying options and their values", some input options (--context --parameters, --plugin, --tags, and --trust) might have multiple values.
Currently, if multiple parameters are passed as follows
```
npx nx deploy app --context firstKey=firstValue --context secondKey=secondValue
```
the deploy command is not properly issued by the nx executor resulting in the following call:
```
cdk.js deploy --context firstKey=firstValue,secondKey=secondValue
```

In the present PR we added the support for the aforementioned kind of options.

# PR Checklist

- [x] Migrations have been added if necessary
- [x] Unit tests have been added or updated if necessary
- [x] e2e tests have been added or updated if necessary
- [x] Changelog has been updated if necessary
- [x] Documentation has been updated if necessary

# Issue
Issue number [627](https://github.com/adrian-goe/nx-aws-cdk-v2/issues/627)

Resolves #

### CODE REVIEW

**Comment by adrian-goe** [comment]
@dvd-88 Thanks for your PR. I'm moving this weekend, so I will look into this PR in detail in the next week.

**Review by adrian-goe — APPROVED** [review]

**Comment by dvd-88** [comment]
@adrian-goe thank you for merging the PR! Could you release a new version of the package?

**Comment by adrian-goe** [comment]
@dvd-88 sure. there is the 1.4.0 as a beta version out now

https://www.npmjs.com/package/@ago-dev/nx-aws-cdk-v2/v/1.4.0

**Comment by dvd-88** [comment]
@adrian-goe thank you!

**Pull request merged**
