### PR TITLE
fix aliases

### LINKED ISSUE #679: cannot use imported stacks and constructs from libs/packages in nx monorepo
There is an issue when importing stacks/constructs in an aws-cdk infra app created using @ago-dev/nx-aws-cdk-v2. 

This was a surprise issue for me given that one of the key reasons to use an nx workspace is to be able to split up projects into different libs/packages and import them into project apps. This approach is recommended by nx's authors nrwl.io as well.

I am not sure however I wonder if this may be related to not using something like `tsconfig-paths/register` or another solution (tsc-alias etc?) to resolve paths in the definition of `nodeCommandWithRelativePath` in `nx-aws-cdk-v2/packages/aws-cdk-v2/src/utils/executor.util.ts`.

If the issue is indeed related to paths, an unrelated project that might be of interest to reference is nx-builders by Web & Söhne that registers TS paths in its solution for supporting ts-node in the monorepo: https://github.com/tailoredmedia/backend-nx-skeleton/tree/master/packages/nx-builders#ts-node-dev. 

Also of potential interest: https://github.com/aws/jsii/issues/865

Replication:
- create a new nx node:lib or js:lib and add a stack or construct to it
- import the stack and/or construct in the aws-cdk infra app created using the generator from @ago-dev/nx-aws-cdk-v2 and rig it up 
- try to deploy the stack
- observe the error "Cannot find module @myorg/my-library" where "@myorg/my-library" is the `importPath` of the package/library within the nx workspace

Example error output from trying to deploy:

```txt
OptionsParsedExecutorInterface {"_":["TestBucketStack"],"parseArgs":{"_":["TestBucketStack"]},"sourceRoot":"apps/infra/src","root":"apps/infra"}
nodeCommandWithRelativePath node /home/username/projects/my-nx-project/node_modules/aws-cdk/bin/cdk.js deploy
Executing command: node /home/username/projects/my-nx-project/node_modules/aws-cdk/bin/cdk.js deploy --_ TestBucketStack
Error: Cannot find module '@myorg/cdk-stacks'
Require stack:
- /home/username/projects/my-nx-project/apps/infra/src/main.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/home/username/projects/my-nx-project/node_modules/.pnpm/@cspotcode+source-map-support@0.8.1/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/username/projects/my-nx-project/apps/infra/src/main.ts:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module.m._compile (/home/username/projects/my-nx-project/node_modules/.pnpm/ts-node@10.9.1_72wjdbglblrsksmmmhzpvueijy/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Object.require.extensions.<computed> [as .ts] (/home/username/projects/my-nx-project/node_modules/.pnpm/ts-node@10.9.1_72wjdbglblrsksmmmhzpvueijy/node_modules/ts-node/src/index.ts:1621:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/username/projects/my-nx-project/apps/infra/src/main.ts' ]
}
```

Versions:
- running current versions of everything including nx 15.8.6 (latest) + @ago-dev/nx-aws-cdk-v2 1.3.1

If there's a way to successfully import constants / functions / constructs + stacks from other libraries within the nx workspace, please let me know! Thanks for your work on this package!

### PR DESCRIPTION
**Pull request by ALMaclaine**
# Description

fixes #679 based on suggestions listed in issue.

@adrian-goe 

# PR Checklist

- [ ] Migrations have been added if necessary
- [ x] Unit tests have been added or updated if necessary
- [ x] e2e tests have been added or updated if necessary
- [ ?] Changelog has been updated if necessary
- [ ] Documentation has been updated if necessary

# Issue

#679 

Resolves #

#679

### CODE REVIEW

**Comment by ALMaclaine** [comment]
@adrian-goe Do you plan on continuing maintenance of this library? Otherwise I'll fork it and keep it alive.

**Comment by adrian-goe** [comment]
@ALMaclaine thanks for your PR.

yes, the plan is to continue.  But I had project graduation last week and before that I moved. But the stressful time is over now.
But support is always welcome.

**Comment by ALMaclaine** [comment]
@adrian-goe cool glad to hear it, thanks for building this plugin, really appreciate it. Feel free to tag me if you ever have any issues you may be too busy for.

**Comment by ALMaclaine** [comment]
@adrian-goe Will you publish a new version please?

**Comment by firxworx** [comment]
@ALMaclaine thanks for the initiative on a PR and offer to maintain this plugin above! Thanks @adrian-goe I really appreciate that you created this package and am glad to see you plan on maintaining it, I was wondering the same thing myself!

**Pull request merged**
